version: "3.9"
services:
  back:
    build: ./back
    container_name: eval_mon_back
    env_file:
      - .env
    depends_on:
      - bdd
    ports:
      - "3000:3000"
    command: ["npm", "start"]
  
  bdd:
    image: mysql:8.4
    container_name: eval_mon_sql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./bdd/data:/data/db
      - ./bdd/dbconfig:/data/configdb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"

volumes:
  dbdata: {}
  dbconfig: {}
